// Single source of truth for all Lyra design tokens.
// Foundation stories (Colors, Effects) display these; preview.jsx injects them as CSS vars.

export const SEMANTIC_SECTIONS = [
  { title: 'Surface', prefix: 'bg/surface/', tokens: [
    { name: 'base',             light: '#FFFFFF',                  dark: '#1F1F1E',                desc: 'Primary content area that all other containers sit on top of. The lightest structural surface.' },
    { name: 'container',        light: '#FFFFFF',                  dark: '#1F1F1E',                desc: 'Main containers background — for panels and cards.' },
    { name: 'container-subtle', light: '#FBFCFE',                  dark: '#262626',                desc: 'A subtle container background for panels and cards that need a slight differentiation from the background.' },
    { name: 'overlay',          light: '#FFFFFF',                  dark: '#2E2E2E',                desc: 'Floating panels, dropdowns, popovers, and tooltips that float above page content.' },
    { name: 'canvas',           light: '#FBFCFE',                  dark: '#141414',                desc: 'Background for visual content areas such as flowcharts and diagrams.' },
    { name: 'shell',            light: '#F5F7F9',                  dark: '#2E2E2E',                desc: 'Background for the suite shell — top bar, side navigation and surrounding content area.' },
    { name: 'backdrop',         light: 'rgba(0,0,0,0.24)',         dark: 'rgba(0,0,0,0.24)',       desc: 'The dim mask behind modals, drawers, and overlays.' },
    { name: 'inverse',          light: '#2A2D32',                  dark: '#ECEFF3',                desc: 'Dark background for inverted panels, inverted tooltips, and elements requiring high contrast against a light surface.' },
  ]},
  { title: 'Background', prefix: 'bg/', tokens: [
    { name: 'primary',          light: '#166CCA',                  dark: '#166CCA',                desc: 'Primary action color — primary buttons, key branded elements.' },
    { name: 'destructive',      light: '#BD2A2A',                  dark: '#BD2A2A',                desc: 'Background for destructive interactive controls.' },
    { name: 'secondary',        light: '#FFFFFF',                  dark: 'rgba(255,255,255,0.04)', desc: 'Secondary buttons & interactive areas.' },
    { name: 'field',            light: '#FFFFFF',                  dark: 'rgba(255,255,255,0.04)', desc: 'Input fields, text areas and any receptive surface that accepts user-entered data.' },
    { name: 'ai',               light: 'rgba(143,115,227,0.04)',   dark: 'rgba(143,115,227,0.08)', desc: 'Background for AI-related elements such as content summarization and recommendations.' },
    { name: 'ai-gradient-start',light: '#7B61FF',                  dark: '#7B61FF',                desc: 'AI orb conic gradient start color.' },
    { name: 'ai-gradient-end',  light: '#3B82F6',                  dark: '#3B82F6',                desc: 'AI orb conic gradient end color.' },
    { name: 'control',          light: '#FFFFFF',                  dark: '#1F1F1E',                desc: 'Compact interactive elements — checkbox, radio button, switch, or track.' },
    { name: 'control-subtle',   light: 'rgba(0,0,0,0.02)',         dark: 'rgba(255,255,255,0.04)', desc: 'A low-opacity control background. Adapts to any background by design.' },
    { name: 'disabled',         light: 'rgba(0,0,0,0.06)',         dark: 'rgba(255,255,255,0.04)', desc: 'Opacity-based background for interactive elements with a fill.' },
    { name: 'none',             light: 'rgba(0,0,0,0)',            dark: 'rgba(255,255,255,0)',    desc: 'Transparent background. Use in interactive elements that don\'t have a visible fill.' },
  ]},
  { title: 'Active Background', prefix: 'bg/active/', tokens: [
    { name: 'strong',   light: '#166CCA',              dark: '#4896EC',               desc: 'High contrast active state — checkboxes, toggle switches and pressed controls.' },
    { name: 'moderate', light: '#D3E6FD',              dark: 'rgba(72,150,236,0.2)',  desc: 'Selected and active states for navigation and menus.' },
    { name: 'subtle',   light: '#F1F7FE',              dark: 'rgba(72,150,236,0.12)', desc: 'A soft active state for active chips, cards and grid rows.' },
  ]},
  { title: 'Conversation', prefix: 'bg/conversation/', tokens: [
    { name: 'AI',       light: '#F5F7F9',              dark: '#FFFFFF',               desc: '' },
    { name: 'agent',    light: '#E5EEFF',              dark: 'rgba(44,138,242,0.18)', desc: '' },
    { name: 'customer', light: '#DEF7E1',              dark: '#0F2A13',               desc: '' },
    { name: 'user',     light: '#E5EEFF',              dark: 'rgba(44,138,242,0.18)', desc: '' },
  ]},
  { title: 'Foreground', prefix: 'fg/', tokens: [
    { name: 'default',          light: 'rgba(0,0,0,0.8)',          dark: 'rgba(255,255,255,0.8)',  desc: 'Primary text and icons.' },
    { name: 'secondary',        light: 'rgba(0,0,0,0.6)',          dark: 'rgba(255,255,255,0.6)',  desc: 'Supporting text — captions, helper text, placeholders and metadata.' },
    { name: 'action',           light: '#5D6A79',                  dark: '#ACB7C3',                desc: 'Interactive affordance color for actionable text, icon buttons.' },
    { name: 'disabled',         light: 'rgba(0,0,0,0.3)',          dark: 'rgba(255,255,255,0.2)',  desc: 'Opacity-based disabled foreground.' },
    { name: 'link',             light: '#185BA4',                  dark: '#A7D0FE',                desc: 'Inline hyperlinks within body text or paragraphs.' },
    { name: 'inverse',          light: '#FFFFFF',                  dark: '#1F1F1E',                desc: 'Text and icons on dark backgrounds.' },
    { name: 'inverse-disabled', light: 'rgba(255,255,255,0.3)',    dark: 'rgba(0,0,0,0.3)',        desc: 'Disabled interactive text or icons on dark backgrounds.' },
    { name: 'on-primary',       light: '#FFFFFF',                  dark: '#FFFFFF',                desc: 'Foreground on primary backgrounds.' },
    { name: 'on-destructive',   light: '#FFFFFF',                  dark: '#FFFFFF',                desc: 'Foreground on destructive elements.' },
  ]},
  { title: 'Active Foreground', prefix: 'fg/active/', tokens: [
    { name: 'strong', light: '#185BA4', dark: '#A7D0FE', desc: 'High-emphasis active text & icons.' },
    { name: 'subtle', light: '#F6FAFE', dark: '#0C2845', desc: 'Softer active text & icons indication.' },
  ]},
  { title: 'Border', prefix: 'border/', tokens: [
    { name: 'subtle',   light: 'rgba(0,0,0,0.1)',          dark: 'rgba(255,255,255,0.1)',  desc: 'Barely visible separator — used mostly for dividers between surface regions.' },
    { name: 'soft',     light: 'rgba(0,0,0,0.16)',         dark: 'rgba(255,255,255,0.16)', desc: 'Standard border for interactive controls and panels.' },
    { name: 'medium',   light: 'rgba(0,0,0,0.32)',         dark: 'rgba(255,255,255,0.32)', desc: 'Emphasis border — when a border requires stronger definition.' },
    { name: 'strong',   light: 'rgba(0,0,0,0.46)',         dark: 'rgba(255,255,255,0.46)', desc: 'High-contrast border for maximum definition.' },
    { name: 'disabled', light: 'rgba(0,0,0,0.1)',          dark: 'rgba(255,255,255,0.1)',  desc: 'Opacity-based disabled control border.' },
    { name: 'none',     light: 'rgba(0,0,0,0)',            dark: 'rgba(255,255,255,0)',    desc: 'Transparent border.' },
    { name: 'active',   light: '#185BA4',                  dark: '#4896EC',                desc: 'Active or selected state border.' },
    { name: 'field-ai', light: '#4E39A8',                  dark: '#A998E7',                desc: '' },
    { name: 'inverse',  light: 'rgba(255,255,255,0.8)',    dark: 'rgba(0,0,0,0.8)',        desc: 'Border for use on dark or inverted backgrounds.' },
  ]},
  { title: 'Focus', prefix: 'border/focus/', tokens: [
    { name: 'default', light: '#185BA4',                dark: '#FACB33',                desc: 'Standard keyboard focus ring for all interactive elements.' },
    { name: 'inverse', light: '#FACB33',                dark: '#185BA4',                desc: 'Focus ring for elements on dark or inverted surfaces.' },
    { name: 'ring',    light: 'rgba(44,138,242,0.25)', dark: 'rgba(44,138,242,0.25)', desc: 'Translucent glow layer applied alongside the focus ring.' },
  ]},
  { title: 'Status', prefix: 'status/', tokens: [
    { name: 'success-strong',  light: '#23722D',              dark: '#64B96F',               desc: 'Success text, icons, and borders.' },
    { name: 'success-medium',  light: '#64B96F',              dark: '#23722D',               desc: 'Moderate success color.' },
    { name: 'success-subtle',  light: '#EBFAED',              dark: 'rgba(33,116,44,0.2)',   desc: 'Success backgrounds.' },
    { name: 'info-strong',     light: '#2D5BB9',              dark: '#789FED',               desc: 'Informational text, icons, and borders.' },
    { name: 'info-medium',     light: '#789FED',              dark: '#2D5BB9',               desc: 'Moderate info color.' },
    { name: 'info-subtle',     light: '#F0F5FF',              dark: 'rgba(37,88,193,0.2)',   desc: 'Info backgrounds.' },
    { name: 'critical-strong', light: '#BD2A2A',              dark: '#FA7F7F',               desc: 'Error and critical text, icons, and borders.' },
    { name: 'critical-medium', light: '#FA7F7F',              dark: '#BD2A2A',               desc: 'Moderate critical color.' },
    { name: 'critical-subtle', light: '#FFF0F0',              dark: 'rgba(227,69,69,0.12)',  desc: 'Error backgrounds.' },
    { name: 'warning-strong',  light: '#8E6800',              dark: '#FACB33',               desc: 'Warning text, icons, and borders.' },
    { name: 'warning-medium',  light: '#FACB33',              dark: '#8E6800',               desc: 'Moderate warning color.' },
    { name: 'warning-subtle',  light: '#FFFAE0',              dark: 'rgba(142,104,0,0.2)',   desc: 'Warning backgrounds.' },
  ]},
  { title: 'Accent', prefix: 'accent/', tokens: [
    { name: 'slate-soft',    light: '#ECEFF3', dark: '#49515A',  desc: 'Adaptive background slightly darker than the parent background.' },
    { name: 'slate-strong',  light: '#5D6A79', dark: '#D0D6DC',  desc: 'Adaptive foreground slightly darker than the parent background.' },
    { name: 'red-soft',      light: '#FFE0E0', dark: '#A32424',  desc: '' },
    { name: 'red-strong',    light: '#BD2A2A', dark: '#FFB8B8',  desc: '' },
    { name: 'orange-soft',   light: '#FFE5CC', dark: '#7D420C',  desc: '' },
    { name: 'orange-strong', light: '#A85000', dark: '#FFCC9E',  desc: '' },
    { name: 'yellow-soft',   light: '#FFF3AD', dark: '#674B13',  desc: '' },
    { name: 'yellow-strong', light: '#8E6800', dark: '#FFE680',  desc: '' },
    { name: 'lime-soft',     light: '#E4F6BB', dark: '#446311',  desc: '' },
    { name: 'lime-strong',   light: '#4E760C', dark: '#C9EA80',  desc: '' },
    { name: 'green-soft',    light: '#D2F4D5', dark: '#1F5C27',  desc: '' },
    { name: 'green-strong',  light: '#23722D', dark: '#B0E8B7',  desc: '' },
    { name: 'teal-soft',     light: '#C8EDEF', dark: '#1B636A',  desc: '' },
    { name: 'teal-strong',   light: '#11737C', dark: '#AAE0E5',  desc: '' },
    { name: 'blue-soft',     light: '#D6E4FF', dark: '#264C97',  desc: '' },
    { name: 'blue-strong',   light: '#2D5BB9', dark: '#B9CEF8',  desc: '' },
    { name: 'purple-soft',   light: '#E6E0FF', dark: '#4E39A8',  desc: '' },
    { name: 'purple-strong', light: '#634DBD', dark: '#D1C9F2',  desc: '' },
    { name: 'pink-soft',     light: '#FFE0F5', dark: '#91296E',  desc: '' },
    { name: 'pink-strong',   light: '#B03887', dark: '#FCCAEB',  desc: '' },
  ]},
  { title: 'Interactive States', prefix: 'state/', tokens: [
    { name: 'bg/hover-opacity',           light: 'rgba(0,0,0,0.04)',    dark: 'rgba(255,255,255,0.06)',  desc: 'Perceptible darkening without altering the base color identity.' },
    { name: 'bg/pressed-opacity',         light: 'rgba(0,0,0,0.08)',    dark: 'rgba(255,255,255,0.12)',  desc: 'Perceptible darkening without altering the base color identity.' },
    { name: 'bg/hover-secondary',         light: '#FBFCFE',             dark: 'rgba(255,255,255,0.1)',   desc: '' },
    { name: 'bg/pressed-secondary',       light: '#F5F7F9',             dark: 'rgba(255,255,255,0.16)',  desc: '' },
    { name: 'bg/hover-active-subtle',     light: '#E8F1FC',             dark: 'rgba(72,150,236,0.18)',   desc: '' },
    { name: 'bg/pressed-active-subtle',   light: '#D3E6FD',             dark: 'rgba(72,150,236,0.24)',   desc: '' },
    { name: 'bg/hover-active-strong',     light: '#185BA4',             dark: '#A7D0FE',                 desc: '' },
    { name: 'bg/pressed-active-strong',   light: '#164479',             dark: '#D3E6FD',                 desc: '' },
    { name: 'bg/hover-primary',           light: '#185BA4',             dark: '#185BA4',                 desc: '' },
    { name: 'bg/pressed-primary',         light: '#164479',             dark: '#164479',                 desc: '' },
    { name: 'bg/hover-critical-strong',   light: '#A32424',             dark: '#A32424',                 desc: '' },
    { name: 'bg/pressed-critical-strong', light: '#8A1F1F',             dark: '#8A1F1F',                 desc: '' },
    { name: 'bg/hover-critical-subtle',   light: '#FFEBEB',             dark: 'rgba(227,69,69,0.18)',    desc: '' },
    { name: 'bg/pressed-critical-subtle', light: '#FFE0E0',             dark: 'rgba(227,69,69,0.24)',    desc: '' },
    { name: 'border/hover-neutral',       light: 'rgba(0,0,0,0.8)',     dark: 'rgba(255,255,255,0.8)',   desc: '' },
  ]},
];

export const SIZE_SECTIONS = [
  { title: 'Spacing', prefix: 'lyra/spacing/', tokens: [
    {n:'0',v:0},{n:'05',v:2},{n:'1',v:4},{n:'2',v:8},{n:'3',v:12},{n:'4',v:16},
    {n:'5',v:20},{n:'6',v:24},{n:'7',v:28},{n:'8',v:32},{n:'9',v:36},{n:'10',v:40},
  ]},
  { title: 'Border Radius', prefix: 'lyra/radius/', tokens: [
    {n:'none',v:0},{n:'xs',v:4},{n:'sm',v:6},{n:'md',v:8},{n:'lg',v:12},{n:'xl',v:16},{n:'round',v:999},
  ]},
  { title: 'Border Width', prefix: 'lyra/border/', tokens: [
    {n:'none',v:0},{n:'default',v:1},{n:'md',v:2},{n:'lg',v:4},
  ]},
  { title: 'Control Height', prefix: 'lyra/control-height/', tokens: [
    {n:'2xs',v:16},{n:'xs',v:20},{n:'sm',v:24},{n:'md',v:32},{n:'lg',v:36},{n:'xl',v:40},
  ]},
  { title: 'Icon Size', prefix: 'lyra/icon-size/', tokens: [
    {n:'xs',v:12},{n:'sm',v:16},{n:'md',v:20},{n:'lg',v:24},
  ]},
  { title: 'Row Height', prefix: 'lyra/row-height/', tokens: [
    {n:'sm',v:32},{n:'md',v:36},{n:'lg',v:40},{n:'xl',v:48},{n:'2xl',v:56},
  ]},
];

export const SHADOWS = [
  { name: 'lyra/shadow/xl',   value: '0px 20px 40px rgba(0, 0, 0, 0.12)', desc: 'Large modals, full-page drawers, or floating panels that dominate the viewport.' },
  { name: 'lyra/shadow/lg',   value: '0px 12px 24px rgba(0, 0, 0, 0.08)', desc: 'Dialogs, side panels, and dropdown menus with significant elevation.' },
  { name: 'lyra/shadow/md',   value: '0px 4px 12px rgba(0, 0, 0, 0.06)',  desc: 'Cards, popovers, and tooltips that sit above the page surface.' },
  { name: 'lyra/shadow/sm',   value: '0px 2px 6px rgba(0, 0, 0, 0.04)',   desc: 'Subtle lift for interactive cards, chips, and inline controls.' },
  { name: 'lyra/shadow/none', value: 'none',                               desc: 'No shadow. Use to explicitly remove elevation from an element.' },
];
